name: Bataviten CI Actions
on:
  push:
    branches: [master, development]
  pull_request:
    branches: [master]
jobs:
  container-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x]
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Running Lint check
        run: npm run lint
      - name: Running Unit Test
        run: ./node_modules/cross-env ZOMATO_API_URL=https://developers.zomato.com/api/v2.1 ZOMATO_API_KEY={{secrets.ZOMATO_API_KEY}} && npm run test
      - name: Build Project
        run: npm run build
